### ISSUE TITLE
Create balance system

### ISSUE THREAD

**Issue by Lustyn** [LittleBigCo/LittleBigNode#2]

**Comment by incinirate** [comment]
Please elaborate

**Comment by Lustyn** [comment]
@incinirate Just need to add some stuff to manage balances, to be completely honest I assigned you for no reason lol

**Comment by Lustyn** [comment]
Partially done: https://github.com/LittleBigCo/LittleBigNode/commit/553236459a7cf1b70bcd6f104dcb45927b4b9ac1

**Comment by Lustyn** [comment]
Done: https://github.com/LittleBigCo/LittleBigNode/commit/a6f22d7196c0bfde0871638b501dd14b928da879
