### ISSUE TITLE
Allow enterprises to apply for custom 0001 - 9998 prefixes

### ISSUE THREAD

**Issue by Lustyn** [LittleBigCo/LittleBigNode#3]
If you wish to reserve your own address block, just leave a comment on this issue and once its all implemented you will have a time period where you can save up the lbc to pay for the block. Although, if you don't claim it within that time it will free up. _NOTE: Only one per person._
# Currently claimed address blocks:

0000 - Single user addresses
0001 - Reserved for connordelaney
2514 - Reserved for awsumben13
9999 - Reserved for internal use

**Comment by ghost** [comment]
Can I claim 0001 please?

**Comment by Lustyn** [comment]
@connordelan Sure.

**Comment by exerro** [comment]
Could I claim 2514 please?

**Comment by Lustyn** [comment]
@awsumben13 Sure.
